$lines = @(
  "import { NextResponse } from 'next/server';",
  "import type { NextRequest } from 'next/server';",
  "import { SUPPORTED_LOCALES, DEFAULT_LOCALE } from '@/lib/i18n';",
  "",
  "const LOCALE_PREFIX_RE = /^\/[a-z]{2}(\/|$)/i;",
  "",
  "export function middleware(request: NextRequest): NextResponse {",
  "  const { pathname } = request.nextUrl;",
  "",
  "  if (",
  "    pathname.startsWith('/_next/') ||",
  "    pathname.startsWith('/api/') ||",
  "    pathname === '/rss.xml' ||",
  "    /\.[a-z0-9]{1,5}$/i.test(pathname)",
  "  ) {",
  "    return NextResponse.next();",
  "  }",
  "",
  "  if (LOCALE_PREFIX_RE.test(pathname)) {",
  "    return NextResponse.next();",
  "  }",
  "",
  "  const cookieLocale = request.cookies.get('locale')?.value;",
  "  const locale =",
  "    cookieLocale && (SUPPORTED_LOCALES as readonly string[]).includes(cookieLocale)",
  "      ? cookieLocale",
  "      : DEFAULT_LOCALE;",
  "",
  "  const sep = pathname === '/' ? '' : pathname;",
  "  const url = request.nextUrl.clone();",
  "  url.pathname = '/' + locale + sep;",
  "",
  "  return NextResponse.redirect(url, { status: 307 });",
  "}",
  "",
  "export const config = {",
  "  matcher: ['/((?!_next/static|_next/image|favicon.ico).*)'],",
  "};"
)
$lines | Set-Content -Path 'C:\simple-deutsch-blog\web\src\middleware.ts' -Encoding UTF8
Write-Host "Written: $(Test-Path 'C:\simple-deutsch-blog\web\src\middleware.ts')"
