export type FrequentWord = {
  word: string;
  article?: "der" | "die" | "das";
  type: "verb" | "noun" | "adj" | "adv";
  translations: {
    en: string;
    ru: string;
    uk: string;
  };
  rank: number;
  example: string;
};

export const FREQUENT_WORDS: FrequentWord[] = [
  // ── Core verbs ──────────────────────────────────────────────────────────
  { rank: 3, word: "machen", type: "verb", translations: { en: "to do, to make", ru: "делать, создавать", uk: "робити, створювати" }, example: "Was machst du heute?" },
  { rank: 5, word: "gehen", type: "verb", translations: { en: "to go, to walk", ru: "идти, ходить", uk: "іти, ходити" }, example: "Ich gehe jeden Morgen spazieren." },
  { rank: 7, word: "kommen", type: "verb", translations: { en: "to come", ru: "приходить", uk: "приходити" }, example: "Wann kommst du nach Hause?" },
  { rank: 9, word: "sagen", type: "verb", translations: { en: "to say, to tell", ru: "говорить, сказать", uk: "казати, говорити" }, example: "Was hat er gesagt?" },
  { rank: 11, word: "sehen", type: "verb", translations: { en: "to see, to watch", ru: "видеть, смотреть", uk: "бачити, дивитися" }, example: "Ich sehe das Problem nicht." },
  { rank: 13, word: "geben", type: "verb", translations: { en: "to give", ru: "давать, дать", uk: "давати, дати" }, example: "Kannst du mir bitte das Salz geben?" },
  { rank: 15, word: "nehmen", type: "verb", translations: { en: "to take", ru: "брать, взять", uk: "брати, взяти" }, example: "Ich nehme den Bus." },
  { rank: 17, word: "wissen", type: "verb", translations: { en: "to know (a fact)", ru: "знать", uk: "знати" }, example: "Ich weiß nicht, wo er ist." },
  { rank: 19, word: "denken", type: "verb", translations: { en: "to think", ru: "думать", uk: "думати" }, example: "Ich denke, das ist eine gute Idee." },
  { rank: 21, word: "stehen", type: "verb", translations: { en: "to stand", ru: "стоять", uk: "стояти" }, example: "Die Vase steht auf dem Tisch." },
  { rank: 23, word: "finden", type: "verb", translations: { en: "to find, to think", ru: "находить, считать", uk: "знаходити, вважати" }, example: "Ich finde diesen Film sehr gut." },
  { rank: 25, word: "lassen", type: "verb", translations: { en: "to let, to leave", ru: "позволять, оставлять", uk: "дозволяти, залишати" }, example: "Lass mich in Ruhe." },
  { rank: 27, word: "bleiben", type: "verb", translations: { en: "to stay, to remain", ru: "оставаться", uk: "залишатися" }, example: "Ich bleibe heute zu Hause." },
  { rank: 29, word: "heißen", type: "verb", translations: { en: "to be called, to mean", ru: "называться, означать", uk: "називатися, означати" }, example: "Wie heißt du?" },
  { rank: 31, word: "glauben", type: "verb", translations: { en: "to believe, to think", ru: "верить, думать", uk: "вірити, думати" }, example: "Ich glaube, er kommt später." },
  { rank: 33, word: "halten", type: "verb", translations: { en: "to hold, to stop", ru: "держать, останавливаться", uk: "тримати, зупинятися" }, example: "Kannst du das kurz halten?" },
  { rank: 35, word: "liegen", type: "verb", translations: { en: "to lie (be located)", ru: "лежать, находиться", uk: "лежати, знаходитися" }, example: "Das Buch liegt auf dem Tisch." },
  { rank: 37, word: "sprechen", type: "verb", translations: { en: "to speak, to talk", ru: "говорить, разговаривать", uk: "говорити, розмовляти" }, example: "Sprichst du Deutsch?" },
  { rank: 39, word: "bringen", type: "verb", translations: { en: "to bring", ru: "приносить, привозить", uk: "приносити, привозити" }, example: "Kannst du mir den Schlüssel bringen?" },
  { rank: 41, word: "leben", type: "verb", translations: { en: "to live", ru: "жить", uk: "жити" }, example: "Ich lebe seit drei Jahren in Berlin." },
  { rank: 43, word: "fahren", type: "verb", translations: { en: "to drive, to travel", ru: "ехать, водить", uk: "їхати, водити" }, example: "Ich fahre jeden Tag mit dem Auto zur Arbeit." },
  { rank: 45, word: "meinen", type: "verb", translations: { en: "to mean, to think", ru: "иметь в виду, считать", uk: "мати на увазі, вважати" }, example: "Was meinst du damit?" },
  { rank: 47, word: "schreiben", type: "verb", translations: { en: "to write", ru: "писать", uk: "писати" }, example: "Ich schreibe eine E-Mail." },
  { rank: 49, word: "lesen", type: "verb", translations: { en: "to read", ru: "читать", uk: "читати" }, example: "Ich lese jeden Abend ein Buch." },
  { rank: 51, word: "spielen", type: "verb", translations: { en: "to play", ru: "играть", uk: "грати" }, example: "Die Kinder spielen im Garten." },
  { rank: 53, word: "arbeiten", type: "verb", translations: { en: "to work", ru: "работать", uk: "працювати" }, example: "Er arbeitet in einem Büro." },
  { rank: 55, word: "kaufen", type: "verb", translations: { en: "to buy", ru: "покупать, купить", uk: "купувати, купити" }, example: "Ich kaufe heute Gemüse." },
  { rank: 57, word: "fragen", type: "verb", translations: { en: "to ask", ru: "спрашивать", uk: "запитувати" }, example: "Darf ich kurz fragen?" },
  { rank: 59, word: "antworten", type: "verb", translations: { en: "to answer", ru: "отвечать", uk: "відповідати" }, example: "Sie hat nicht geantwortet." },
  { rank: 61, word: "öffnen", type: "verb", translations: { en: "to open", ru: "открывать", uk: "відкривати" }, example: "Bitte öffne das Fenster." },
  { rank: 63, word: "schließen", type: "verb", translations: { en: "to close", ru: "закрывать", uk: "закривати" }, example: "Der Laden schließt um 20 Uhr." },
  { rank: 65, word: "hören", type: "verb", translations: { en: "to hear, to listen", ru: "слышать, слушать", uk: "чути, слухати" }, example: "Ich höre gerne Musik." },
  { rank: 67, word: "essen", type: "verb", translations: { en: "to eat", ru: "есть, кушать", uk: "їсти" }, example: "Was möchtest du essen?" },
  { rank: 69, word: "trinken", type: "verb", translations: { en: "to drink", ru: "пить", uk: "пити" }, example: "Ich trinke morgens Kaffee." },
  { rank: 71, word: "schlafen", type: "verb", translations: { en: "to sleep", ru: "спать", uk: "спати" }, example: "Ich schlafe genug." },
  { rank: 73, word: "lernen", type: "verb", translations: { en: "to learn, to study", ru: "учиться, изучать", uk: "вчитися, вивчати" }, example: "Er lernt Deutsch seit einem Jahr." },
  { rank: 75, word: "helfen", type: "verb", translations: { en: "to help", ru: "помогать", uk: "допомагати" }, example: "Kannst du mir helfen?" },
  { rank: 77, word: "zeigen", type: "verb", translations: { en: "to show, to point", ru: "показывать", uk: "показувати" }, example: "Kannst du mir den Weg zeigen?" },
  { rank: 79, word: "suchen", type: "verb", translations: { en: "to search, to look for", ru: "искать", uk: "шукати" }, example: "Ich suche meine Schlüssel." },
  { rank: 81, word: "warten", type: "verb", translations: { en: "to wait", ru: "ждать", uk: "чекати" }, example: "Wir warten auf den Bus." },
  { rank: 83, word: "verstehen", type: "verb", translations: { en: "to understand", ru: "понимать", uk: "розуміти" }, example: "Ich verstehe nicht, was du meinst." },
  { rank: 85, word: "brauchen", type: "verb", translations: { en: "to need, to require", ru: "нуждаться, требовать", uk: "потребувати" }, example: "Ich brauche deine Hilfe." },
  { rank: 87, word: "beginnen", type: "verb", translations: { en: "to begin, to start", ru: "начинать", uk: "починати" }, example: "Der Kurs beginnt um 9 Uhr." },
  { rank: 89, word: "vergessen", type: "verb", translations: { en: "to forget", ru: "забывать", uk: "забувати" }, example: "Ich habe meinen Schlüssel vergessen." },
  { rank: 91, word: "erklären", type: "verb", translations: { en: "to explain", ru: "объяснять", uk: "пояснювати" }, example: "Kannst du das bitte erklären?" },
  { rank: 93, word: "kennen", type: "verb", translations: { en: "to know (a person)", ru: "знать (человека)", uk: "знати (людину)" }, example: "Kennst du diesen Mann?" },
  { rank: 95, word: "treffen", type: "verb", translations: { en: "to meet", ru: "встречать, встречаться", uk: "зустрічати, зустрічатися" }, example: "Wir treffen uns um 14 Uhr." },
  { rank: 97, word: "bestellen", type: "verb", translations: { en: "to order", ru: "заказывать", uk: "замовляти" }, example: "Ich möchte bitte bestellen." },
  { rank: 99, word: "bezahlen", type: "verb", translations: { en: "to pay", ru: "платить, оплачивать", uk: "платити, оплачувати" }, example: "Wie möchten Sie bezahlen?" },

  // ── Time and number concepts ─────────────────────────────────────────────
  { rank: 101, word: "Termin", article: "der", type: "noun", translations: { en: "appointment, meeting", ru: "встреча, запись", uk: "зустріч, запис" }, example: "Ich habe morgen einen Termin beim Arzt." },
  { rank: 103, word: "Stunde", article: "die", type: "noun", translations: { en: "hour", ru: "час (единица времени)", uk: "година" }, example: "Ich warte schon eine Stunde." },
  { rank: 105, word: "Minute", article: "die", type: "noun", translations: { en: "minute", ru: "минута", uk: "хвилина" }, example: "Der Bus kommt in fünf Minuten." },
  { rank: 107, word: "Woche", article: "die", type: "noun", translations: { en: "week", ru: "неделя", uk: "тиждень" }, example: "Nächste Woche habe ich Urlaub." },
  { rank: 109, word: "Monat", article: "der", type: "noun", translations: { en: "month", ru: "месяц", uk: "місяць" }, example: "Ich bin seit einem Monat hier." },
  { rank: 111, word: "Uhrzeit", article: "die", type: "noun", translations: { en: "time (of day)", ru: "время (суток)", uk: "час доби" }, example: "Welche Uhrzeit ist es?" },
  { rank: 113, word: "Datum", article: "das", type: "noun", translations: { en: "date, datum", ru: "дата", uk: "дата" }, example: "Welches Datum haben wir heute?" },

  // ── Family and people ────────────────────────────────────────────────────
  { rank: 115, word: "Familie", article: "die", type: "noun", translations: { en: "family", ru: "семья", uk: "сім'я" }, example: "Meine Familie wohnt in München." },
  { rank: 117, word: "Freund", article: "der", type: "noun", translations: { en: "friend, boyfriend", ru: "друг, парень", uk: "друг, хлопець" }, example: "Das ist mein bester Freund." },
  { rank: 119, word: "Freundin", article: "die", type: "noun", translations: { en: "friend, girlfriend", ru: "подруга, девушка", uk: "подруга, дівчина" }, example: "Meine Freundin kommt heute." },
  { rank: 121, word: "Nachbar", article: "der", type: "noun", translations: { en: "neighbour", ru: "сосед", uk: "сусід" }, example: "Mein Nachbar ist sehr nett." },
  { rank: 123, word: "Kollege", article: "der", type: "noun", translations: { en: "colleague", ru: "коллега", uk: "колега" }, example: "Mein Kollege hilft mir bei der Arbeit." },
  { rank: 125, word: "Chef", article: "der", type: "noun", translations: { en: "boss, manager", ru: "начальник, шеф", uk: "начальник, шеф" }, example: "Mein Chef ist heute nicht im Büro." },
  { rank: 127, word: "Arzt", article: "der", type: "noun", translations: { en: "doctor (male)", ru: "врач", uk: "лікар" }, example: "Ich brauche einen Termin beim Arzt." },
  { rank: 129, word: "Ärztin", article: "die", type: "noun", translations: { en: "doctor (female)", ru: "врач (женщина)", uk: "лікарка" }, example: "Die Ärztin hat mir ein Rezept gegeben." },
  { rank: 131, word: "Schüler", article: "der", type: "noun", translations: { en: "pupil, student", ru: "ученик, школьник", uk: "учень, школяр" }, example: "Die Schüler machen ihre Hausaufgaben." },
  { rank: 133, word: "Student", article: "der", type: "noun", translations: { en: "university student", ru: "студент", uk: "студент" }, example: "Er ist Student an der Universität Berlin." },
  { rank: 135, word: "Lehrer", article: "der", type: "noun", translations: { en: "teacher (male)", ru: "учитель", uk: "вчитель" }, example: "Unser Lehrer ist sehr geduldig." },

  // ── Body and health ──────────────────────────────────────────────────────
  { rank: 137, word: "Kopf", article: "der", type: "noun", translations: { en: "head", ru: "голова", uk: "голова" }, example: "Mir tut der Kopf weh." },
  { rank: 139, word: "Hand", article: "die", type: "noun", translations: { en: "hand", ru: "рука (кисть)", uk: "рука (долоня)" }, example: "Gib mir die Hand." },
  { rank: 141, word: "Auge", article: "das", type: "noun", translations: { en: "eye", ru: "глаз", uk: "око" }, example: "Sie hat schöne blaue Augen." },
  { rank: 143, word: "Rücken", article: "der", type: "noun", translations: { en: "back (of body)", ru: "спина", uk: "спина" }, example: "Mein Rücken schmerzt." },
  { rank: 145, word: "Bauch", article: "der", type: "noun", translations: { en: "belly, stomach", ru: "живот", uk: "живіт" }, example: "Mir tut der Bauch weh." },
  { rank: 147, word: "Bein", article: "das", type: "noun", translations: { en: "leg", ru: "нога (от бедра)", uk: "нога" }, example: "Ich habe mir das Bein verletzt." },
  { rank: 149, word: "Zahn", article: "der", type: "noun", translations: { en: "tooth", ru: "зуб", uk: "зуб" }, example: "Mir tut ein Zahn weh." },
  { rank: 151, word: "Fieber", article: "das", type: "noun", translations: { en: "fever, temperature", ru: "температура, жар", uk: "температура, жар" }, example: "Ich habe Fieber." },
  { rank: 153, word: "Schmerz", article: "der", type: "noun", translations: { en: "pain, ache", ru: "боль", uk: "біль" }, example: "Ich habe Schmerzen im Knie." },
  { rank: 155, word: "Erkältung", article: "die", type: "noun", translations: { en: "cold (illness)", ru: "простуда", uk: "застуда" }, example: "Ich habe eine Erkältung." },
  { rank: 157, word: "Rezept", article: "das", type: "noun", translations: { en: "prescription, recipe", ru: "рецепт", uk: "рецепт" }, example: "Der Arzt hat mir ein Rezept ausgestellt." },
  { rank: 159, word: "Tablette", article: "die", type: "noun", translations: { en: "tablet, pill", ru: "таблетка", uk: "таблетка" }, example: "Ich nehme drei Tabletten pro Tag." },
  { rank: 161, word: "Krankenhaus", article: "das", type: "noun", translations: { en: "hospital", ru: "больница", uk: "лікарня" }, example: "Er musste ins Krankenhaus." },
  { rank: 163, word: "Apotheke", article: "die", type: "noun", translations: { en: "pharmacy", ru: "аптека", uk: "аптека" }, example: "Gibt es eine Apotheke in der Nähe?" },

  // ── Food and drink ───────────────────────────────────────────────────────
  { rank: 165, word: "Brot", article: "das", type: "noun", translations: { en: "bread", ru: "хлеб", uk: "хліб" }, example: "Ich esse morgens Brot mit Butter." },
  { rank: 167, word: "Brötchen", article: "das", type: "noun", translations: { en: "bread roll", ru: "булочка", uk: "булочка" }, example: "Vier Brötchen, bitte." },
  { rank: 169, word: "Butter", article: "die", type: "noun", translations: { en: "butter", ru: "масло (сливочное)", uk: "вершкове масло" }, example: "Ich streiche Butter aufs Brot." },
  { rank: 171, word: "Käse", article: "der", type: "noun", translations: { en: "cheese", ru: "сыр", uk: "сир" }, example: "Ich mag Käse sehr gerne." },
  { rank: 173, word: "Fleisch", article: "das", type: "noun", translations: { en: "meat", ru: "мясо", uk: "м'ясо" }, example: "Ich esse selten Fleisch." },
  { rank: 175, word: "Gemüse", article: "das", type: "noun", translations: { en: "vegetables", ru: "овощи", uk: "овочі" }, example: "Iss mehr Gemüse!" },
  { rank: 177, word: "Obst", article: "das", type: "noun", translations: { en: "fruit", ru: "фрукты", uk: "фрукти" }, example: "Ich kaufe jeden Tag frisches Obst." },
  { rank: 179, word: "Milch", article: "die", type: "noun", translations: { en: "milk", ru: "молоко", uk: "молоко" }, example: "Ich trinke morgens ein Glas Milch." },
  { rank: 181, word: "Ei", article: "das", type: "noun", translations: { en: "egg", ru: "яйцо", uk: "яйце" }, example: "Ich esse jeden Morgen ein Ei." },
  { rank: 183, word: "Zucker", article: "der", type: "noun", translations: { en: "sugar", ru: "сахар", uk: "цукор" }, example: "Ich nehme keinen Zucker im Kaffee." },
  { rank: 185, word: "Salz", article: "das", type: "noun", translations: { en: "salt", ru: "соль", uk: "сіль" }, example: "Kannst du mir das Salz geben?" },
  { rank: 187, word: "Öl", article: "das", type: "noun", translations: { en: "oil", ru: "масло (растительное)", uk: "олія" }, example: "Ich brate das Fleisch in Öl." },
  { rank: 189, word: "Wasser", article: "das", type: "noun", translations: { en: "water", ru: "вода", uk: "вода" }, example: "Ein Glas Wasser, bitte." },
  { rank: 191, word: "Kaffee", article: "der", type: "noun", translations: { en: "coffee", ru: "кофе", uk: "кава" }, example: "Ich brauche morgens meinen Kaffee." },
  { rank: 193, word: "Tee", article: "der", type: "noun", translations: { en: "tea", ru: "чай", uk: "чай" }, example: "Möchtest du Tee oder Kaffee?" },
  { rank: 195, word: "Bier", article: "das", type: "noun", translations: { en: "beer", ru: "пиво", uk: "пиво" }, example: "Ein Bier, bitte." },
  { rank: 197, word: "Wein", article: "der", type: "noun", translations: { en: "wine", ru: "вино", uk: "вино" }, example: "Ich trinke gerne ein Glas Wein." },
  { rank: 199, word: "Saft", article: "der", type: "noun", translations: { en: "juice", ru: "сок", uk: "сік" }, example: "Ein Glas Orangensaft, bitte." },
  { rank: 201, word: "Suppe", article: "die", type: "noun", translations: { en: "soup", ru: "суп", uk: "суп" }, example: "Ich esse mittags oft Suppe." },
  { rank: 203, word: "Kuchen", article: "der", type: "noun", translations: { en: "cake", ru: "торт, кекс", uk: "торт, кекс" }, example: "Zum Geburtstag gibt es Kuchen." },
  { rank: 205, word: "Schokolade", article: "die", type: "noun", translations: { en: "chocolate", ru: "шоколад", uk: "шоколад" }, example: "Ich liebe dunkle Schokolade." },
  { rank: 207, word: "Frühstück", article: "das", type: "noun", translations: { en: "breakfast", ru: "завтрак", uk: "сніданок" }, example: "Das Frühstück ist von 7 bis 10 Uhr." },
  { rank: 209, word: "Mittagessen", article: "das", type: "noun", translations: { en: "lunch", ru: "обед", uk: "обід" }, example: "Lass uns zusammen Mittagessen!" },
  { rank: 211, word: "Abendessen", article: "das", type: "noun", translations: { en: "dinner, supper", ru: "ужин", uk: "вечеря" }, example: "Was gibt es zum Abendessen?" },

  // ── Places and buildings ─────────────────────────────────────────────────
  { rank: 213, word: "Bahnhof", article: "der", type: "noun", translations: { en: "train station", ru: "вокзал", uk: "вокзал" }, example: "Wo ist der nächste Bahnhof?" },
  { rank: 215, word: "Flughafen", article: "der", type: "noun", translations: { en: "airport", ru: "аэропорт", uk: "аеропорт" }, example: "Der Flug startet vom Flughafen München." },
  { rank: 217, word: "Hotel", article: "das", type: "noun", translations: { en: "hotel", ru: "отель", uk: "готель" }, example: "Ich habe ein Zimmer im Hotel gebucht." },
  { rank: 219, word: "Restaurant", article: "das", type: "noun", translations: { en: "restaurant", ru: "ресторан", uk: "ресторан" }, example: "Wir essen heute im Restaurant." },
  { rank: 221, word: "Supermarkt", article: "der", type: "noun", translations: { en: "supermarket", ru: "супермаркет", uk: "супермаркет" }, example: "Ich gehe schnell in den Supermarkt." },
  { rank: 223, word: "Schule", article: "die", type: "noun", translations: { en: "school", ru: "школа", uk: "школа" }, example: "Mein Kind geht in die Schule." },
  { rank: 225, word: "Universität", article: "die", type: "noun", translations: { en: "university", ru: "университет", uk: "університет" }, example: "Sie studiert an der Universität." },
  { rank: 227, word: "Bibliothek", article: "die", type: "noun", translations: { en: "library", ru: "библиотека", uk: "бібліотека" }, example: "Ich gehe in die Bibliothek, um zu lernen." },
  { rank: 229, word: "Museum", article: "das", type: "noun", translations: { en: "museum", ru: "музей", uk: "музей" }, example: "Das Museum ist dienstags geschlossen." },
  { rank: 231, word: "Krankenhaus", article: "das", type: "noun", translations: { en: "hospital", ru: "больница", uk: "лікарня" }, example: "Das nächste Krankenhaus ist zwei Kilometer entfernt." },
  { rank: 233, word: "Büro", article: "das", type: "noun", translations: { en: "office", ru: "офис", uk: "офіс" }, example: "Ich arbeite im Büro im dritten Stock." },
  { rank: 235, word: "Marktplatz", article: "der", type: "noun", translations: { en: "market square", ru: "рыночная площадь", uk: "ринкова площа" }, example: "Der Marktplatz liegt im Zentrum der Stadt." },
  { rank: 237, word: "Rathaus", article: "das", type: "noun", translations: { en: "town hall", ru: "ратуша, мэрия", uk: "ратуша, міська рада" }, example: "Das Standesamt befindet sich im Rathaus." },
  { rank: 239, word: "Post", article: "die", type: "noun", translations: { en: "post office, mail", ru: "почта", uk: "пошта" }, example: "Ich muss zum Paket zur Post bringen." },
  { rank: 241, word: "Polizei", article: "die", type: "noun", translations: { en: "police", ru: "полиция", uk: "поліція" }, example: "Im Notfall ruf die Polizei an." },
  { rank: 243, word: "Kirche", article: "die", type: "noun", translations: { en: "church", ru: "церковь", uk: "церква" }, example: "Die alte Kirche steht im Zentrum." },
  { rank: 245, word: "Hafen", article: "der", type: "noun", translations: { en: "harbour, port", ru: "порт, гавань", uk: "порт, гавань" }, example: "Das Schiff fährt in den Hafen ein." },

  // ── Transportation ───────────────────────────────────────────────────────
  { rank: 247, word: "Auto", article: "das", type: "noun", translations: { en: "car", ru: "автомобиль, машина", uk: "автомобіль, машина" }, example: "Ich fahre mit dem Auto." },
  { rank: 249, word: "Bus", article: "der", type: "noun", translations: { en: "bus", ru: "автобус", uk: "автобус" }, example: "Der Bus kommt in zehn Minuten." },
  { rank: 251, word: "Zug", article: "der", type: "noun", translations: { en: "train", ru: "поезд", uk: "поїзд" }, example: "Ich nehme den Zug nach Hamburg." },
  { rank: 253, word: "U-Bahn", article: "die", type: "noun", translations: { en: "metro, underground", ru: "метро", uk: "метро" }, example: "Die U-Bahn kommt alle fünf Minuten." },
  { rank: 255, word: "Straßenbahn", article: "die", type: "noun", translations: { en: "tram", ru: "трамвай", uk: "трамвай" }, example: "Die Straßenbahn fährt direkt zur Schule." },
  { rank: 257, word: "Fahrrad", article: "das", type: "noun", translations: { en: "bicycle", ru: "велосипед", uk: "велосипед" }, example: "Ich fahre mit dem Fahrrad zur Arbeit." },
  { rank: 259, word: "Flugzeug", article: "das", type: "noun", translations: { en: "airplane", ru: "самолёт", uk: "літак" }, example: "Das Flugzeug landet um 14 Uhr." },
  { rank: 261, word: "Fahrkarte", article: "die", type: "noun", translations: { en: "ticket (transport)", ru: "билет", uk: "квиток" }, example: "Wo kann ich eine Fahrkarte kaufen?" },
  { rank: 263, word: "Haltestelle", article: "die", type: "noun", translations: { en: "bus/tram stop", ru: "остановка", uk: "зупинка" }, example: "Die Haltestelle ist um die Ecke." },
  { rank: 265, word: "Verspätung", article: "die", type: "noun", translations: { en: "delay", ru: "опоздание, задержка", uk: "запізнення, затримка" }, example: "Der Zug hat zwanzig Minuten Verspätung." },
  { rank: 267, word: "Führerschein", article: "der", type: "noun", translations: { en: "driving licence", ru: "водительское удостоверение", uk: "водійське посвідчення" }, example: "Ich muss meinen Führerschein verlängern." },
  { rank: 269, word: "Stau", article: "der", type: "noun", translations: { en: "traffic jam", ru: "пробка", uk: "корок, затор" }, example: "Es gibt einen langen Stau auf der Autobahn." },
  { rank: 271, word: "Ausgang", article: "der", type: "noun", translations: { en: "exit, way out", ru: "выход", uk: "вихід" }, example: "Der Ausgang ist links." },
  { rank: 273, word: "Eingang", article: "der", type: "noun", translations: { en: "entrance", ru: "вход", uk: "вхід" }, example: "Der Eingang befindet sich vorne." },

  // ── Work and education ───────────────────────────────────────────────────
  { rank: 275, word: "Arbeit", article: "die", type: "noun", translations: { en: "work, job", ru: "работа", uk: "робота" }, example: "Wie ist deine Arbeit?" },
  { rank: 277, word: "Beruf", article: "der", type: "noun", translations: { en: "profession, job", ru: "профессия", uk: "професія" }, example: "Was ist dein Beruf?" },
  { rank: 279, word: "Firma", article: "die", type: "noun", translations: { en: "company, firm", ru: "фирма, компания", uk: "фірма, компанія" }, example: "Er arbeitet in einer großen Firma." },
  { rank: 281, word: "Gehalt", article: "das", type: "noun", translations: { en: "salary", ru: "зарплата", uk: "зарплата" }, example: "Das Gehalt wird monatlich überwiesen." },
  { rank: 283, word: "Urlaub", article: "der", type: "noun", translations: { en: "holiday, vacation", ru: "отпуск, каникулы", uk: "відпустка, канікули" }, example: "Ich fahre im Sommer in den Urlaub." },
  { rank: 285, word: "Bewerbung", article: "die", type: "noun", translations: { en: "job application", ru: "заявление о приёме на работу", uk: "заява про прийом на роботу" }, example: "Ich schicke morgen meine Bewerbung ab." },
  { rank: 287, word: "Lebenslauf", article: "der", type: "noun", translations: { en: "CV, résumé", ru: "резюме", uk: "резюме" }, example: "Schick mir deinen Lebenslauf." },
  { rank: 289, word: "Ausbildung", article: "die", type: "noun", translations: { en: "training, education", ru: "образование, подготовка", uk: "освіта, підготовка" }, example: "Ich mache eine Ausbildung zum Koch." },
  { rank: 291, word: "Prüfung", article: "die", type: "noun", translations: { en: "exam, test", ru: "экзамен, зачёт", uk: "іспит, залік" }, example: "Morgen habe ich eine wichtige Prüfung." },
  { rank: 293, word: "Zeugnis", article: "das", type: "noun", translations: { en: "report card, certificate", ru: "свидетельство, аттестат", uk: "свідоцтво, атестат" }, example: "Ich habe ein gutes Zeugnis bekommen." },
  { rank: 295, word: "Konferenz", article: "die", type: "noun", translations: { en: "conference, meeting", ru: "конференция, совещание", uk: "конференція, нарада" }, example: "Die Konferenz beginnt um 10 Uhr." },
  { rank: 297, word: "Besprechung", article: "die", type: "noun", translations: { en: "meeting, discussion", ru: "встреча, обсуждение", uk: "зустріч, обговорення" }, example: "Ich habe eine Besprechung mit dem Team." },

  // ── Home and objects ─────────────────────────────────────────────────────
  { rank: 299, word: "Wohnung", article: "die", type: "noun", translations: { en: "apartment, flat", ru: "квартира", uk: "квартира" }, example: "Ich habe eine neue Wohnung gemietet." },
  { rank: 301, word: "Zimmer", article: "das", type: "noun", translations: { en: "room", ru: "комната", uk: "кімната" }, example: "Ich hätte gerne ein ruhiges Zimmer." },
  { rank: 303, word: "Küche", article: "die", type: "noun", translations: { en: "kitchen", ru: "кухня", uk: "кухня" }, example: "Die Küche ist gut ausgestattet." },
  { rank: 305, word: "Schlüssel", article: "der", type: "noun", translations: { en: "key", ru: "ключ", uk: "ключ" }, example: "Ich habe meinen Schlüssel verloren." },
  { rank: 307, word: "Miete", article: "die", type: "noun", translations: { en: "rent", ru: "аренда, плата за аренду", uk: "оренда, плата за оренду" }, example: "Die Miete ist hier sehr teuer." },
  { rank: 309, word: "Möbel", article: "die", type: "noun", translations: { en: "furniture", ru: "мебель", uk: "меблі" }, example: "Wir brauchen noch mehr Möbel." },
  { rank: 311, word: "Heizung", article: "die", type: "noun", translations: { en: "heating, radiator", ru: "отопление, батарея", uk: "опалення, батарея" }, example: "Die Heizung funktioniert nicht." },
  { rank: 313, word: "Strom", article: "der", type: "noun", translations: { en: "electricity, current", ru: "электричество, ток", uk: "електрика, струм" }, example: "Der Strom ist ausgefallen." },
  { rank: 315, word: "Waschmaschine", article: "die", type: "noun", translations: { en: "washing machine", ru: "стиральная машина", uk: "пральна машина" }, example: "Meine Waschmaschine ist kaputt." },
  { rank: 317, word: "Kühlschrank", article: "der", type: "noun", translations: { en: "fridge, refrigerator", ru: "холодильник", uk: "холодильник" }, example: "Der Kühlschrank ist fast leer." },

  // ── Shopping and money ───────────────────────────────────────────────────
  { rank: 319, word: "Preis", article: "der", type: "noun", translations: { en: "price, prize", ru: "цена, приз", uk: "ціна, приз" }, example: "Was ist der Preis für dieses Produkt?" },
  { rank: 321, word: "Rechnung", article: "die", type: "noun", translations: { en: "bill, invoice", ru: "счёт, счёт-фактура", uk: "рахунок, рахунок-фактура" }, example: "Kann ich bitte die Rechnung haben?" },
  { rank: 323, word: "Quittung", article: "die", type: "noun", translations: { en: "receipt", ru: "квитанция, чек", uk: "квитанція, чек" }, example: "Ich brauche eine Quittung." },
  { rank: 325, word: "Rabatt", article: "der", type: "noun", translations: { en: "discount", ru: "скидка", uk: "знижка" }, example: "Gibt es einen Rabatt für Studenten?" },
  { rank: 327, word: "Angebot", article: "das", type: "noun", translations: { en: "offer, deal, supply", ru: "предложение, акция", uk: "пропозиція, акція" }, example: "Das ist ein tolles Angebot." },
  { rank: 329, word: "Kasse", article: "die", type: "noun", translations: { en: "checkout, till", ru: "касса", uk: "каса" }, example: "Bitte zahlen Sie an der Kasse." },
  { rank: 331, word: "Bargeld", article: "das", type: "noun", translations: { en: "cash", ru: "наличные", uk: "готівка" }, example: "Haben Sie Bargeld dabei?" },
  { rank: 333, word: "Kreditkarte", article: "die", type: "noun", translations: { en: "credit card", ru: "кредитная карта", uk: "кредитна картка" }, example: "Kann ich mit Kreditkarte zahlen?" },
  { rank: 335, word: "Tasche", article: "die", type: "noun", translations: { en: "bag, pocket", ru: "сумка, карман", uk: "сумка, кишеня" }, example: "Ich habe meine Tasche vergessen." },
  { rank: 337, word: "Kleidung", article: "die", type: "noun", translations: { en: "clothing, clothes", ru: "одежда", uk: "одяг" }, example: "Ich brauche wärmere Kleidung für den Winter." },
  { rank: 339, word: "Größe", article: "die", type: "noun", translations: { en: "size", ru: "размер", uk: "розмір" }, example: "Welche Größe haben Sie?" },

  // ── Communication and technology ─────────────────────────────────────────
  { rank: 341, word: "Handy", article: "das", type: "noun", translations: { en: "mobile phone", ru: "мобильный телефон", uk: "мобільний телефон" }, example: "Mein Handy hat keinen Akku mehr." },
  { rank: 343, word: "Nachricht", article: "die", type: "noun", translations: { en: "message, news", ru: "сообщение, новость", uk: "повідомлення, новина" }, example: "Ich schicke dir eine Nachricht." },
  { rank: 345, word: "E-Mail", article: "die", type: "noun", translations: { en: "email", ru: "электронная почта", uk: "електронна пошта" }, example: "Ich warte auf deine E-Mail." },
  { rank: 347, word: "Passwort", article: "das", type: "noun", translations: { en: "password", ru: "пароль", uk: "пароль" }, example: "Ich habe mein Passwort vergessen." },
  { rank: 349, word: "Internet", article: "das", type: "noun", translations: { en: "internet", ru: "интернет", uk: "інтернет" }, example: "Das Internet hier ist sehr langsam." },
  { rank: 351, word: "Website", article: "die", type: "noun", translations: { en: "website", ru: "сайт", uk: "сайт" }, example: "Die Information steht auf unserer Website." },
  { rank: 353, word: "App", article: "die", type: "noun", translations: { en: "app, application", ru: "приложение", uk: "додаток" }, example: "Lad die App auf dein Handy." },
  { rank: 355, word: "Akku", article: "der", type: "noun", translations: { en: "battery (rechargeable)", ru: "аккумулятор", uk: "акумулятор" }, example: "Mein Akku ist leer." },
  { rank: 357, word: "Drucker", article: "der", type: "noun", translations: { en: "printer", ru: "принтер", uk: "принтер" }, example: "Der Drucker ist kaputt." },
  { rank: 359, word: "Bildschirm", article: "der", type: "noun", translations: { en: "screen, display", ru: "экран, монитор", uk: "екран, монітор" }, example: "Der Bildschirm flackert." },

  // ── Common adjectives ────────────────────────────────────────────────────
  { rank: 361, word: "wichtig", type: "adj", translations: { en: "important", ru: "важный", uk: "важливий" }, example: "Das ist eine sehr wichtige Frage." },
  { rank: 363, word: "richtig", type: "adj", translations: { en: "correct, right", ru: "правильный, верный", uk: "правильний, вірний" }, example: "Bist du sicher, dass das richtig ist?" },
  { rank: 365, word: "falsch", type: "adj", translations: { en: "wrong, false", ru: "неправильный, ложный", uk: "неправильний, хибний" }, example: "Diese Antwort ist falsch." },
  { rank: 367, word: "möglich", type: "adj", translations: { en: "possible", ru: "возможный", uk: "можливий" }, example: "Ist es möglich, morgen zu kommen?" },
  { rank: 369, word: "nötig", type: "adj", translations: { en: "necessary", ru: "необходимый", uk: "необхідний" }, example: "Ist das wirklich nötig?" },
  { rank: 371, word: "einfach", type: "adj", translations: { en: "simple, easy, single", ru: "простой, лёгкий", uk: "простий, легкий" }, example: "Das Rezept ist ganz einfach." },
  { rank: 373, word: "schwierig", type: "adj", translations: { en: "difficult, hard", ru: "трудный, сложный", uk: "важкий, складний" }, example: "Deutsch ist manchmal schwierig." },
  { rank: 375, word: "gleich", type: "adj", translations: { en: "same, equal, right away", ru: "одинаковый, сразу", uk: "однаковий, зараз" }, example: "Ich komme gleich." },
  { rank: 377, word: "fertig", type: "adj", translations: { en: "ready, finished, done", ru: "готовый, законченный", uk: "готовий, закінчений" }, example: "Bist du schon fertig?" },
  { rank: 379, word: "bereit", type: "adj", translations: { en: "ready, prepared", ru: "готовый, подготовленный", uk: "готовий, підготовлений" }, example: "Ich bin bereit." },
  { rank: 381, word: "kostenlos", type: "adj", translations: { en: "free (of charge), gratis", ru: "бесплатный", uk: "безкоштовний" }, example: "Der Eintritt ist kostenlos." },
  { rank: 383, word: "günstig", type: "adj", translations: { en: "cheap, affordable, favourable", ru: "дешёвый, выгодный", uk: "дешевий, вигідний" }, example: "Das Hotel ist sehr günstig." },
  { rank: 385, word: "teuer", type: "adj", translations: { en: "expensive", ru: "дорогой", uk: "дорогий" }, example: "Das ist zu teuer für mich." },
  { rank: 387, word: "frisch", type: "adj", translations: { en: "fresh", ru: "свежий", uk: "свіжий" }, example: "Das Brot ist noch frisch." },
  { rank: 389, word: "voll", type: "adj", translations: { en: "full, crowded", ru: "полный, заполненный", uk: "повний, заповнений" }, example: "Der Bus ist schon voll." },
  { rank: 391, word: "leer", type: "adj", translations: { en: "empty", ru: "пустой", uk: "порожній" }, example: "Die Flasche ist leer." },
  { rank: 393, word: "sauber", type: "adj", translations: { en: "clean", ru: "чистый", uk: "чистий" }, example: "Das Hotel ist sehr sauber." },
  { rank: 395, word: "schmutzig", type: "adj", translations: { en: "dirty", ru: "грязный", uk: "брудний" }, example: "Die Hände sind schmutzig." },
  { rank: 397, word: "warm", type: "adj", translations: { en: "warm", ru: "тёплый", uk: "теплий" }, example: "Heute ist es sehr warm." },
  { rank: 399, word: "kalt", type: "adj", translations: { en: "cold", ru: "холодный", uk: "холодний" }, example: "Das Wasser ist zu kalt." },
  { rank: 401, word: "heiß", type: "adj", translations: { en: "hot", ru: "горячий", uk: "гарячий" }, example: "Vorsicht, das ist heiß!" },
  { rank: 403, word: "langsam", type: "adj", translations: { en: "slow, slowly", ru: "медленный, медленно", uk: "повільний, повільно" }, example: "Bitte sprich langsamer." },
  { rank: 405, word: "schnell", type: "adj", translations: { en: "fast, quick", ru: "быстрый, быстро", uk: "швидкий, швидко" }, example: "Das geht sehr schnell." },
  { rank: 407, word: "laut", type: "adj", translations: { en: "loud, noisy", ru: "громкий, шумный", uk: "гучний, галасливий" }, example: "Die Musik ist zu laut." },
  { rank: 409, word: "leise", type: "adj", translations: { en: "quiet, soft", ru: "тихий, мягкий", uk: "тихий, тихо" }, example: "Sprich bitte leiser!" },

  // ── Adjectives: emotions and states ─────────────────────────────────────
  { rank: 411, word: "glücklich", type: "adj", translations: { en: "happy, lucky", ru: "счастливый", uk: "щасливий" }, example: "Ich bin sehr glücklich." },
  { rank: 413, word: "traurig", type: "adj", translations: { en: "sad", ru: "грустный, печальный", uk: "сумний" }, example: "Warum bist du so traurig?" },
  { rank: 415, word: "müde", type: "adj", translations: { en: "tired", ru: "усталый", uk: "втомлений" }, example: "Ich bin sehr müde." },
  { rank: 417, word: "hungrig", type: "adj", translations: { en: "hungry", ru: "голодный", uk: "голодний" }, example: "Ich bin total hungrig." },
  { rank: 419, word: "krank", type: "adj", translations: { en: "sick, ill", ru: "больной", uk: "хворий" }, example: "Sie ist krank und bleibt zu Hause." },
  { rank: 421, word: "gesund", type: "adj", translations: { en: "healthy", ru: "здоровый", uk: "здоровий" }, example: "Ich versuche, gesund zu leben." },
  { rank: 423, word: "nervös", type: "adj", translations: { en: "nervous, anxious", ru: "нервный, волнующийся", uk: "нервовий, схвильований" }, example: "Ich bin vor dem Gespräch nervös." },
  { rank: 425, word: "aufgeregt", type: "adj", translations: { en: "excited, agitated", ru: "взволнованный", uk: "збуджений, схвильований" }, example: "Die Kinder sind ganz aufgeregt." },
  { rank: 427, word: "überrascht", type: "adj", translations: { en: "surprised", ru: "удивлённый", uk: "здивований" }, example: "Ich bin sehr überrascht." },
  { rank: 429, word: "zufrieden", type: "adj", translations: { en: "satisfied, content", ru: "довольный", uk: "задоволений" }, example: "Ich bin sehr zufrieden mit dem Ergebnis." },

  // ── Nature and weather ───────────────────────────────────────────────────
  { rank: 431, word: "Wetter", article: "das", type: "noun", translations: { en: "weather", ru: "погода", uk: "погода" }, example: "Das Wetter ist heute schön." },
  { rank: 433, word: "Regen", article: "der", type: "noun", translations: { en: "rain", ru: "дождь", uk: "дощ" }, example: "Es gibt morgen Regen." },
  { rank: 435, word: "Schnee", article: "der", type: "noun", translations: { en: "snow", ru: "снег", uk: "сніг" }, example: "Im Winter gibt es hier viel Schnee." },
  { rank: 437, word: "Sonne", article: "die", type: "noun", translations: { en: "sun", ru: "солнце", uk: "сонце" }, example: "Die Sonne scheint heute." },
  { rank: 439, word: "Wind", article: "der", type: "noun", translations: { en: "wind", ru: "ветер", uk: "вітер" }, example: "Es ist viel Wind heute." },
  { rank: 441, word: "Wolke", article: "die", type: "noun", translations: { en: "cloud", ru: "облако", uk: "хмара" }, example: "Heute ist es bewölkt." },
  { rank: 443, word: "Temperatur", article: "die", type: "noun", translations: { en: "temperature", ru: "температура", uk: "температура" }, example: "Die Temperatur fällt unter null Grad." },
  { rank: 445, word: "Jahreszeit", article: "die", type: "noun", translations: { en: "season", ru: "время года", uk: "пора року" }, example: "Welche Jahreszeit magst du am liebsten?" },
  { rank: 447, word: "Frühling", article: "der", type: "noun", translations: { en: "spring", ru: "весна", uk: "весна" }, example: "Im Frühling blühen die Blumen." },
  { rank: 449, word: "Sommer", article: "der", type: "noun", translations: { en: "summer", ru: "лето", uk: "літо" }, example: "Im Sommer fahre ich ans Meer." },
  { rank: 451, word: "Herbst", article: "der", type: "noun", translations: { en: "autumn, fall", ru: "осень", uk: "осінь" }, example: "Im Herbst fallen die Blätter von den Bäumen." },
  { rank: 453, word: "Winter", article: "der", type: "noun", translations: { en: "winter", ru: "зима", uk: "зима" }, example: "Im Winter ist es hier sehr kalt." },

  // ── B1–B2 verbs ──────────────────────────────────────────────────────────
  { rank: 455, word: "erreichen", type: "verb", translations: { en: "to reach, to achieve", ru: "достигать, добираться", uk: "досягати, дістатися" }, example: "Ich konnte das Ziel erreichen." },
  { rank: 457, word: "entscheiden", type: "verb", translations: { en: "to decide", ru: "принимать решение", uk: "вирішувати" }, example: "Ich muss mich bald entscheiden." },
  { rank: 459, word: "verbessern", type: "verb", translations: { en: "to improve", ru: "улучшать", uk: "покращувати" }, example: "Ich möchte mein Deutsch verbessern." },
  { rank: 461, word: "erinnern", type: "verb", translations: { en: "to remind, to remember", ru: "напоминать, помнить", uk: "нагадувати, пам'ятати" }, example: "Ich erinnere mich nicht mehr daran." },
  { rank: 463, word: "empfehlen", type: "verb", translations: { en: "to recommend", ru: "рекомендовать", uk: "рекомендувати" }, example: "Kannst du ein gutes Restaurant empfehlen?" },
  { rank: 465, word: "versprechen", type: "verb", translations: { en: "to promise", ru: "обещать", uk: "обіцяти" }, example: "Ich verspreche, pünktlich zu sein." },
  { rank: 467, word: "erlauben", type: "verb", translations: { en: "to allow, to permit", ru: "разрешать, позволять", uk: "дозволяти" }, example: "Ist es erlaubt, hier zu parken?" },
  { rank: 469, word: "vermeiden", type: "verb", translations: { en: "to avoid", ru: "избегать", uk: "уникати" }, example: "Du solltest Süßigkeiten vermeiden." },
  { rank: 471, word: "überzeugen", type: "verb", translations: { en: "to convince, to persuade", ru: "убеждать", uk: "переконувати" }, example: "Er hat mich nicht überzeugt." },
  { rank: 473, word: "beachten", type: "verb", translations: { en: "to pay attention, to observe", ru: "обращать внимание, соблюдать", uk: "зважати, дотримуватися" }, example: "Bitte beachten Sie die Hinweise." },
  { rank: 475, word: "übersetzen", type: "verb", translations: { en: "to translate", ru: "переводить", uk: "перекладати" }, example: "Kannst du das für mich übersetzen?" },
  { rank: 477, word: "vereinbaren", type: "verb", translations: { en: "to arrange, to agree on", ru: "договариваться, назначать", uk: "домовлятися, призначати" }, example: "Wir müssen einen neuen Termin vereinbaren." },
  { rank: 479, word: "vergleichen", type: "verb", translations: { en: "to compare", ru: "сравнивать", uk: "порівнювати" }, example: "Ich möchte die Preise vergleichen." },
  { rank: 481, word: "benutzen", type: "verb", translations: { en: "to use", ru: "использовать", uk: "використовувати" }, example: "Darf ich dein Telefon benutzen?" },
  { rank: 483, word: "überprüfen", type: "verb", translations: { en: "to check, to verify", ru: "проверять", uk: "перевіряти" }, example: "Bitte überprüfe noch mal die Adresse." },
  { rank: 485, word: "vorbereiten", type: "verb", translations: { en: "to prepare", ru: "подготавливать, готовиться", uk: "готуватися, підготовляти" }, example: "Ich bereite mich auf die Prüfung vor." },
  { rank: 487, word: "teilnehmen", type: "verb", translations: { en: "to participate, to attend", ru: "принимать участие", uk: "брати участь" }, example: "Ich nehme an dem Kurs teil." },
  { rank: 489, word: "abbrechen", type: "verb", translations: { en: "to cancel, to break off", ru: "отменять, прерывать", uk: "скасовувати, припиняти" }, example: "Die Veranstaltung musste abgebrochen werden." },
  { rank: 491, word: "aufhören", type: "verb", translations: { en: "to stop, to quit", ru: "прекращать, бросать", uk: "припиняти, кидати" }, example: "Hör bitte auf zu reden." },
  { rank: 493, word: "ausdrücken", type: "verb", translations: { en: "to express", ru: "выражать", uk: "виражати" }, example: "Ich kann das nicht gut ausdrücken." },

  // ── B1–B2 nouns ──────────────────────────────────────────────────────────
  { rank: 495, word: "Erfahrung", article: "die", type: "noun", translations: { en: "experience", ru: "опыт", uk: "досвід" }, example: "Ich habe viel Erfahrung in diesem Bereich." },
  { rank: 497, word: "Möglichkeit", article: "die", type: "noun", translations: { en: "possibility, opportunity", ru: "возможность", uk: "можливість" }, example: "Gibt es eine Möglichkeit, früher zu kommen?" },
  { rank: 499, word: "Lösung", article: "die", type: "noun", translations: { en: "solution", ru: "решение", uk: "рішення" }, example: "Wir suchen eine gute Lösung." },
  { rank: 501, word: "Zusammenfassung", article: "die", type: "noun", translations: { en: "summary", ru: "резюме, краткое изложение", uk: "резюме, короткий виклад" }, example: "Kannst du eine kurze Zusammenfassung geben?" },
  { rank: 503, word: "Verantwortung", article: "die", type: "noun", translations: { en: "responsibility", ru: "ответственность", uk: "відповідальність" }, example: "Das liegt in meiner Verantwortung." },
  { rank: 505, word: "Gelegenheit", article: "die", type: "noun", translations: { en: "opportunity, occasion", ru: "возможность, случай", uk: "нагода, можливість" }, example: "Das ist eine gute Gelegenheit." },
  { rank: 507, word: "Entscheidung", article: "die", type: "noun", translations: { en: "decision", ru: "решение", uk: "рішення" }, example: "Das war die richtige Entscheidung." },
  { rank: 509, word: "Vorschlag", article: "der", type: "noun", translations: { en: "suggestion, proposal", ru: "предложение", uk: "пропозиція" }, example: "Ich habe einen Vorschlag." },
  { rank: 511, word: "Unterschied", article: "der", type: "noun", translations: { en: "difference", ru: "разница, отличие", uk: "різниця, відмінність" }, example: "Was ist der Unterschied?" },
  { rank: 513, word: "Fortschritt", article: "der", type: "noun", translations: { en: "progress", ru: "прогресс, успех", uk: "прогрес, успіх" }, example: "Du machst gute Fortschritte." },
  { rank: 515, word: "Schwierigkeit", article: "die", type: "noun", translations: { en: "difficulty", ru: "трудность, сложность", uk: "труднощі, складність" }, example: "Ich habe Schwierigkeiten mit der Aussprache." },
  { rank: 517, word: "Veranstaltung", article: "die", type: "noun", translations: { en: "event", ru: "мероприятие", uk: "захід" }, example: "Die Veranstaltung findet am Samstag statt." },
  { rank: 519, word: "Übersetzung", article: "die", type: "noun", translations: { en: "translation", ru: "перевод", uk: "переклад" }, example: "Kannst du mir bei der Übersetzung helfen?" },
  { rank: 521, word: "Abschnitt", article: "der", type: "noun", translations: { en: "section, paragraph", ru: "раздел, параграф", uk: "розділ, параграф" }, example: "Lesen Sie den zweiten Abschnitt." },
  { rank: 523, word: "Bedeutung", article: "die", type: "noun", translations: { en: "meaning, significance", ru: "значение, смысл", uk: "значення, сенс" }, example: "Was ist die Bedeutung dieses Wortes?" },
  { rank: 525, word: "Einfluss", article: "der", type: "noun", translations: { en: "influence", ru: "влияние", uk: "вплив" }, example: "Das hat großen Einfluss auf mein Leben." },
  { rank: 527, word: "Kenntnisse", article: "die", type: "noun", translations: { en: "knowledge, skills", ru: "знания, навыки", uk: "знання, навички" }, example: "Ich habe gute Kenntnisse in Englisch." },
  { rank: 529, word: "Widerspruch", article: "der", type: "noun", translations: { en: "contradiction, objection", ru: "противоречие, возражение", uk: "протиріччя, заперечення" }, example: "Sein Verhalten ist ein Widerspruch." },
  { rank: 531, word: "Zustimmung", article: "die", type: "noun", translations: { en: "agreement, approval", ru: "согласие, одобрение", uk: "згода, схвалення" }, example: "Ich brauche deine Zustimmung." },
  { rank: 533, word: "Ablehnung", article: "die", type: "noun", translations: { en: "rejection, refusal", ru: "отказ, отклонение", uk: "відмова" }, example: "Ich habe eine Ablehnung bekommen." },
  { rank: 535, word: "Genehmigung", article: "die", type: "noun", translations: { en: "permission, approval", ru: "разрешение, одобрение", uk: "дозвіл, схвалення" }, example: "Ich warte auf die Genehmigung." },

  // ── B1-B2 adjectives ─────────────────────────────────────────────────────
  { rank: 537, word: "zuverlässig", type: "adj", translations: { en: "reliable, dependable", ru: "надёжный", uk: "надійний" }, example: "Er ist ein zuverlässiger Mitarbeiter." },
  { rank: 539, word: "pünktlich", type: "adj", translations: { en: "punctual, on time", ru: "пунктуальный", uk: "пунктуальний" }, example: "Der Zug ist heute pünktlich." },
  { rank: 541, word: "flexibel", type: "adj", translations: { en: "flexible", ru: "гибкий", uk: "гнучкий" }, example: "Ich bin zeitlich sehr flexibel." },
  { rank: 543, word: "höflich", type: "adj", translations: { en: "polite, courteous", ru: "вежливый", uk: "ввічливий" }, example: "Er ist immer sehr höflich." },
  { rank: 545, word: "deutlich", type: "adj", translations: { en: "clear, distinct", ru: "чёткий, ясный", uk: "чіткий, ясний" }, example: "Sprich bitte deutlicher." },
  { rank: 547, word: "geduldig", type: "adj", translations: { en: "patient", ru: "терпеливый", uk: "терплячий" }, example: "Du musst geduldig sein." },
  { rank: 549, word: "neugierig", type: "adj", translations: { en: "curious, nosy", ru: "любопытный", uk: "цікавий, допитливий" }, example: "Ich bin neugierig, was passiert ist." },
  { rank: 551, word: "ehrlich", type: "adj", translations: { en: "honest, sincere", ru: "честный", uk: "чесний" }, example: "Sei bitte ehrlich mit mir." },
  { rank: 553, word: "selbstständig", type: "adj", translations: { en: "independent, self-employed", ru: "самостоятельный, независимый", uk: "самостійний, незалежний" }, example: "Ich arbeite selbstständig von zu Hause." },
  { rank: 555, word: "aufmerksam", type: "adj", translations: { en: "attentive, mindful", ru: "внимательный", uk: "уважний" }, example: "Sei in der Klasse aufmerksam." },

  // ── Common adverbs and conjunctions ─────────────────────────────────────
  { rank: 557, word: "vielleicht", type: "adv", translations: { en: "maybe, perhaps", ru: "может быть, возможно", uk: "можливо, може бути" }, example: "Vielleicht komme ich morgen." },
  { rank: 559, word: "wahrscheinlich", type: "adv", translations: { en: "probably, likely", ru: "вероятно, скорее всего", uk: "мабуть, ймовірно" }, example: "Er kommt wahrscheinlich zu spät." },
  { rank: 561, word: "trotzdem", type: "adv", translations: { en: "nevertheless, still", ru: "всё равно, тем не менее", uk: "все одно, тим не менш" }, example: "Es regnet, aber ich gehe trotzdem." },
  { rank: 563, word: "deshalb", type: "adv", translations: { en: "therefore, that is why", ru: "поэтому", uk: "тому, ось чому" }, example: "Er ist krank, deshalb kommt er nicht." },
  { rank: 565, word: "außerdem", type: "adv", translations: { en: "besides, moreover", ru: "кроме того, к тому же", uk: "крім того" }, example: "Außerdem habe ich keine Zeit." },
  { rank: 567, word: "obwohl", type: "adv", translations: { en: "although, even though", ru: "хотя, несмотря на то что", uk: "хоча, незважаючи на те що" }, example: "Obwohl es kalt ist, gehe ich spazieren." },
  { rank: 569, word: "sobald", type: "adv", translations: { en: "as soon as", ru: "как только", uk: "як тільки" }, example: "Ruf mich an, sobald du ankommst." },
  { rank: 571, word: "seitdem", type: "adv", translations: { en: "since then, ever since", ru: "с тех пор", uk: "відтоді" }, example: "Seitdem sehe ich ihn täglich." },
  { rank: 573, word: "inzwischen", type: "adv", translations: { en: "meanwhile, by now", ru: "тем временем, уже", uk: "тим часом, вже" }, example: "Ich habe inzwischen eine Lösung gefunden." },
  { rank: 575, word: "eigentlich", type: "adv", translations: { en: "actually, in fact", ru: "собственно, вообще-то", uk: "власне, по суті" }, example: "Was willst du eigentlich?" },
  { rank: 577, word: "ungefähr", type: "adv", translations: { en: "approximately, about", ru: "примерно, около", uk: "приблизно, близько" }, example: "Es dauert ungefähr eine Stunde." },
  { rank: 579, word: "mindestens", type: "adv", translations: { en: "at least", ru: "по крайней мере, минимум", uk: "принаймні, мінімум" }, example: "Ich brauche mindestens eine Stunde." },
  { rank: 581, word: "höchstens", type: "adv", translations: { en: "at most", ru: "максимум, не более", uk: "максимум, не більше" }, example: "Es dauert höchstens zwei Stunden." },
  { rank: 583, word: "bereits", type: "adv", translations: { en: "already", ru: "уже", uk: "вже" }, example: "Ich habe das bereits erledigt." },
  { rank: 585, word: "sofort", type: "adv", translations: { en: "immediately, at once", ru: "немедленно, сразу", uk: "негайно, зараз" }, example: "Komm sofort her!" },

  // ── More useful nouns ────────────────────────────────────────────────────
  { rank: 587, word: "Beispiel", article: "das", type: "noun", translations: { en: "example", ru: "пример", uk: "приклад" }, example: "Kannst du ein Beispiel geben?" },
  { rank: 589, word: "Ergebnis", article: "das", type: "noun", translations: { en: "result, outcome", ru: "результат, итог", uk: "результат, підсумок" }, example: "Das Ergebnis war gut." },
  { rank: 591, word: "Grund", article: "der", type: "noun", translations: { en: "reason, ground", ru: "причина, основание", uk: "причина, підстава" }, example: "Was ist der Grund dafür?" },
  { rank: 593, word: "Ziel", article: "das", type: "noun", translations: { en: "goal, target, destination", ru: "цель, назначение", uk: "мета, призначення" }, example: "Was ist dein Ziel?" },
  { rank: 595, word: "Plan", article: "der", type: "noun", translations: { en: "plan, schedule", ru: "план", uk: "план" }, example: "Hast du einen Plan?" },
  { rank: 597, word: "Schritt", article: "der", type: "noun", translations: { en: "step", ru: "шаг", uk: "крок" }, example: "Das ist der erste Schritt." },
  { rank: 599, word: "Inhalt", article: "der", type: "noun", translations: { en: "content, contents", ru: "содержание", uk: "зміст" }, example: "Was ist der Inhalt dieser E-Mail?" },
  { rank: 601, word: "Thema", article: "das", type: "noun", translations: { en: "topic, subject, theme", ru: "тема", uk: "тема" }, example: "Was ist das Thema des Artikels?" },
  { rank: 603, word: "Antwort", article: "die", type: "noun", translations: { en: "answer, reply", ru: "ответ", uk: "відповідь" }, example: "Ich warte auf deine Antwort." },
  { rank: 605, word: "Frage", article: "die", type: "noun", translations: { en: "question", ru: "вопрос", uk: "питання" }, example: "Ich habe eine Frage." },
  { rank: 607, word: "Hinweis", article: "der", type: "noun", translations: { en: "hint, tip, note", ru: "подсказка, указание", uk: "підказка, вказівка" }, example: "Das ist ein nützlicher Hinweis." },
  { rank: 609, word: "Bericht", article: "der", type: "noun", translations: { en: "report", ru: "отчёт, доклад", uk: "звіт, доповідь" }, example: "Ich muss einen Bericht schreiben." },
  { rank: 611, word: "Anfang", article: "der", type: "noun", translations: { en: "beginning, start", ru: "начало", uk: "початок" }, example: "Am Anfang war es schwierig." },
  { rank: 613, word: "Ende", article: "das", type: "noun", translations: { en: "end, ending", ru: "конец, окончание", uk: "кінець, кінцівка" }, example: "Am Ende war alles gut." },
  { rank: 615, word: "Mitte", article: "die", type: "noun", translations: { en: "middle, centre", ru: "середина, центр", uk: "середина, центр" }, example: "In der Mitte der Stadt." },
  { rank: 617, word: "Schritt", article: "der", type: "noun", translations: { en: "step, pace", ru: "шаг, ход", uk: "крок, хід" }, example: "Schritt für Schritt wirst du besser." },
  { rank: 619, word: "Fehler", article: "der", type: "noun", translations: { en: "mistake, error", ru: "ошибка", uk: "помилка" }, example: "Ich habe einen Fehler gemacht." },
  { rank: 621, word: "Erinnerung", article: "die", type: "noun", translations: { en: "memory, reminder", ru: "воспоминание, напоминание", uk: "спогад, нагадування" }, example: "Das ist eine schöne Erinnerung." },
  { rank: 623, word: "Gewohnheit", article: "die", type: "noun", translations: { en: "habit, custom", ru: "привычка", uk: "звичка" }, example: "Alte Gewohnheiten sind schwer zu ändern." },
  { rank: 625, word: "Verhalten", article: "das", type: "noun", translations: { en: "behaviour, conduct", ru: "поведение", uk: "поведінка" }, example: "Sein Verhalten hat mich überrascht." },
  { rank: 627, word: "Hintergrund", article: "der", type: "noun", translations: { en: "background", ru: "фон, предыстория", uk: "фон, передісторія" }, example: "Was ist der Hintergrund dieser Geschichte?" },
  { rank: 629, word: "Zusammenhang", article: "der", type: "noun", translations: { en: "context, connection", ru: "контекст, связь", uk: "контекст, зв'язок" }, example: "Ich verstehe den Zusammenhang nicht." },
  { rank: 631, word: "Einstellung", article: "die", type: "noun", translations: { en: "attitude, setting", ru: "отношение, установка", uk: "ставлення, налаштування" }, example: "Ich mag seine positive Einstellung." },
  { rank: 633, word: "Absicht", article: "die", type: "noun", translations: { en: "intention, purpose", ru: "намерение, цель", uk: "намір, мета" }, example: "Ich hatte keine böse Absicht." },
  { rank: 635, word: "Wirkung", article: "die", type: "noun", translations: { en: "effect, impact", ru: "эффект, воздействие", uk: "ефект, вплив" }, example: "Das hat eine große Wirkung." },

  // ── More useful verbs ────────────────────────────────────────────────────
  { rank: 637, word: "buchen", type: "verb", translations: { en: "to book, to reserve", ru: "бронировать, заказывать", uk: "бронювати, замовляти" }, example: "Ich habe ein Hotel gebucht." },
  { rank: 639, word: "mieten", type: "verb", translations: { en: "to rent, to hire", ru: "арендовать, снимать", uk: "орендувати, знімати" }, example: "Wir möchten ein Auto mieten." },
  { rank: 641, word: "wechseln", type: "verb", translations: { en: "to change, to switch", ru: "менять, переключать", uk: "міняти, перемикати" }, example: "Ich möchte die Sprache wechseln." },
  { rank: 643, word: "klingeln", type: "verb", translations: { en: "to ring (bell/phone)", ru: "звонить", uk: "дзвонити (у двері)" }, example: "Es klingelt an der Tür." },
  { rank: 645, word: "umziehen", type: "verb", translations: { en: "to move (house)", ru: "переезжать", uk: "переїжджати" }, example: "Ich ziehe nächsten Monat um." },
  { rank: 647, word: "aufstehen", type: "verb", translations: { en: "to get up, to stand up", ru: "вставать", uk: "вставати" }, example: "Ich stehe jeden Morgen um 7 Uhr auf." },
  { rank: 649, word: "einschlafen", type: "verb", translations: { en: "to fall asleep", ru: "засыпать", uk: "засинати" }, example: "Ich kann nicht einschlafen." },
  { rank: 651, word: "aufpassen", type: "verb", translations: { en: "to be careful, to watch out", ru: "быть осторожным, следить", uk: "бути обережним, стежити" }, example: "Pass auf, das ist gefährlich!" },
  { rank: 653, word: "nachfragen", type: "verb", translations: { en: "to inquire, to follow up", ru: "уточнять, переспрашивать", uk: "уточнювати, перепитувати" }, example: "Ich sage dir Bescheid, wenn ich nachgefragt habe." },
  { rank: 655, word: "anmelden", type: "verb", translations: { en: "to register, to sign up", ru: "регистрироваться, записываться", uk: "реєструватися, записуватися" }, example: "Ich muss mich für den Kurs anmelden." },
  { rank: 657, word: "abmelden", type: "verb", translations: { en: "to deregister, to unsubscribe", ru: "отписаться, отменить регистрацию", uk: "відписатися, скасувати реєстрацію" }, example: "Ich möchte mich von dem Newsletter abmelden." },
  { rank: 659, word: "ausfüllen", type: "verb", translations: { en: "to fill in, to complete (form)", ru: "заполнять (форму)", uk: "заповнювати (форму)" }, example: "Bitte füllen Sie das Formular aus." },
  { rank: 661, word: "unterschreiben", type: "verb", translations: { en: "to sign", ru: "подписывать", uk: "підписувати" }, example: "Bitte hier unterschreiben." },
  { rank: 663, word: "drucken", type: "verb", translations: { en: "to print", ru: "печатать, распечатывать", uk: "роздруковувати" }, example: "Kannst du das bitte drucken?" },
  { rank: 665, word: "kopieren", type: "verb", translations: { en: "to copy", ru: "копировать", uk: "копіювати" }, example: "Ich muss dieses Dokument kopieren." },
  { rank: 667, word: "überweisen", type: "verb", translations: { en: "to transfer (money)", ru: "переводить (деньги)", uk: "переказувати (гроші)" }, example: "Ich werde das Geld überweisen." },
  { rank: 669, word: "abheben", type: "verb", translations: { en: "to withdraw (money)", ru: "снимать (деньги)", uk: "знімати (гроші)" }, example: "Ich muss Geld abheben." },
  { rank: 671, word: "einzahlen", type: "verb", translations: { en: "to deposit (money)", ru: "вносить (деньги)", uk: "вносити (гроші)" }, example: "Ich möchte Geld einzahlen." },

  // ── Documents and bureaucracy ─────────────────────────────────────────────
  { rank: 673, word: "Ausweis", article: "der", type: "noun", translations: { en: "ID card, identity card", ru: "удостоверение личности", uk: "посвідчення особи" }, example: "Darf ich Ihren Ausweis sehen?" },
  { rank: 675, word: "Reisepass", article: "der", type: "noun", translations: { en: "passport", ru: "паспорт", uk: "паспорт" }, example: "Ich brauche meinen Reisepass für die Reise." },
  { rank: 677, word: "Visa", article: "das", type: "noun", translations: { en: "visa", ru: "виза", uk: "віза" }, example: "Ich brauche ein Visum für dieses Land." },
  { rank: 679, word: "Formular", article: "das", type: "noun", translations: { en: "form (to fill in)", ru: "бланк, форма", uk: "бланк, форма" }, example: "Bitte füllen Sie dieses Formular aus." },
  { rank: 681, word: "Vertrag", article: "der", type: "noun", translations: { en: "contract, agreement", ru: "договор, контракт", uk: "договір, контракт" }, example: "Ich habe den Vertrag unterschrieben." },
  { rank: 683, word: "Antrag", article: "der", type: "noun", translations: { en: "application, request", ru: "заявка, заявление", uk: "заява, заявка" }, example: "Ich stelle einen Antrag auf Verlängerung." },
  { rank: 685, word: "Bescheinigung", article: "die", type: "noun", translations: { en: "certificate, confirmation", ru: "справка, подтверждение", uk: "довідка, підтвердження" }, example: "Ich brauche eine Bescheinigung vom Arzt." },
  { rank: 687, word: "Versicherung", article: "die", type: "noun", translations: { en: "insurance", ru: "страхование, страховка", uk: "страхування, страховка" }, example: "Haben Sie eine Krankenversicherung?" },
  { rank: 689, word: "Abonnement", article: "das", type: "noun", translations: { en: "subscription", ru: "подписка, абонемент", uk: "підписка, абонемент" }, example: "Ich kündige mein Abonnement." },
  { rank: 691, word: "Kündigung", article: "die", type: "noun", translations: { en: "cancellation, termination", ru: "расторжение, увольнение", uk: "розірвання, звільнення" }, example: "Ich schreibe eine Kündigung." },

  // ── Daily routine ─────────────────────────────────────────────────────────
  { rank: 693, word: "Alltag", article: "der", type: "noun", translations: { en: "everyday life, routine", ru: "повседневная жизнь, рутина", uk: "повсякденне життя, рутина" }, example: "Das gehört zu meinem Alltag." },
  { rank: 695, word: "Routine", article: "die", type: "noun", translations: { en: "routine", ru: "рутина, распорядок", uk: "рутина, розпорядок" }, example: "Ich habe eine feste Morgenroutine." },
  { rank: 697, word: "Aufgabe", article: "die", type: "noun", translations: { en: "task, assignment", ru: "задача, задание", uk: "завдання" }, example: "Das ist meine wichtigste Aufgabe." },
  { rank: 699, word: "Termin", article: "der", type: "noun", translations: { en: "appointment, deadline", ru: "дедлайн, срок", uk: "дедлайн, терміни" }, example: "Der Abgabetermin ist morgen." },
  { rank: 701, word: "Pause", article: "die", type: "noun", translations: { en: "break, pause", ru: "перерыв, пауза", uk: "перерва, пауза" }, example: "Ich brauche eine kurze Pause." },
  { rank: 703, word: "Protokoll", article: "das", type: "noun", translations: { en: "minutes, log, protocol", ru: "протокол, журнал", uk: "протокол, журнал" }, example: "Wer schreibt das Protokoll?" },

  // ── Media and culture ─────────────────────────────────────────────────────
  { rank: 705, word: "Film", article: "der", type: "noun", translations: { en: "film, movie", ru: "фильм, кино", uk: "фільм, кіно" }, example: "Dieser Film ist sehr gut." },
  { rank: 707, word: "Musik", article: "die", type: "noun", translations: { en: "music", ru: "музыка", uk: "музика" }, example: "Ich höre gerne Musik." },
  { rank: 709, word: "Konzert", article: "das", type: "noun", translations: { en: "concert", ru: "концерт", uk: "концерт" }, example: "Ich gehe morgen auf ein Konzert." },
  { rank: 711, word: "Ausstellung", article: "die", type: "noun", translations: { en: "exhibition", ru: "выставка", uk: "виставка" }, example: "Die Ausstellung ist bis Ende des Monats." },
  { rank: 713, word: "Nachrichten", article: "die", type: "noun", translations: { en: "news", ru: "новости", uk: "новини" }, example: "Hast du die Nachrichten gehört?" },
  { rank: 715, word: "Kanal", article: "der", type: "noun", translations: { en: "channel, canal", ru: "канал", uk: "канал" }, example: "Auf welchem Kanal läuft das?" },
  { rank: 717, word: "Sendung", article: "die", type: "noun", translations: { en: "broadcast, programme", ru: "передача, программа", uk: "передача, програма" }, example: "Diese Sendung läuft jeden Montag." },
  { rank: 719, word: "Veröffentlichung", article: "die", type: "noun", translations: { en: "publication, release", ru: "публикация, релиз", uk: "публікація, реліз" }, example: "Die Veröffentlichung ist nächste Woche." },

  // ── More B2 vocabulary ────────────────────────────────────────────────────
  { rank: 721, word: "Schlussfolgerung", article: "die", type: "noun", translations: { en: "conclusion", ru: "вывод, заключение", uk: "висновок" }, example: "Was ist deine Schlussfolgerung?" },
  { rank: 723, word: "Herausforderung", article: "die", type: "noun", translations: { en: "challenge", ru: "вызов, испытание", uk: "виклик, випробування" }, example: "Das ist eine große Herausforderung." },
  { rank: 725, word: "Zusammenarbeit", article: "die", type: "noun", translations: { en: "cooperation, teamwork", ru: "сотрудничество", uk: "співпраця" }, example: "Gute Zusammenarbeit ist wichtig." },
  { rank: 727, word: "Aufmerksamkeit", article: "die", type: "noun", translations: { en: "attention", ru: "внимание", uk: "увага" }, example: "Diese Sache braucht deine Aufmerksamkeit." },
  { rank: 729, word: "Beziehung", article: "die", type: "noun", translations: { en: "relationship, relation", ru: "отношения", uk: "стосунки, відносини" }, example: "Wir haben eine gute Beziehung." },
  { rank: 731, word: "Entwicklung", article: "die", type: "noun", translations: { en: "development", ru: "развитие", uk: "розвиток" }, example: "Die Entwicklung geht schnell voran." },
  { rank: 733, word: "Gesellschaft", article: "die", type: "noun", translations: { en: "society, company", ru: "общество, компания", uk: "суспільство, компанія" }, example: "Das ist ein Problem der Gesellschaft." },
  { rank: 735, word: "Wirtschaft", article: "die", type: "noun", translations: { en: "economy, business", ru: "экономика, хозяйство", uk: "економіка, господарство" }, example: "Die Wirtschaft wächst langsam." },
  { rank: 737, word: "Umgebung", article: "die", type: "noun", translations: { en: "surroundings, environment", ru: "окружение, среда", uk: "оточення, середовище" }, example: "Ich lebe in einer schönen Umgebung." },
  { rank: 739, word: "Umwelt", article: "die", type: "noun", translations: { en: "environment, nature", ru: "окружающая среда", uk: "навколишнє середовище" }, example: "Wir müssen die Umwelt schützen." },
  { rank: 741, word: "Situation", article: "die", type: "noun", translations: { en: "situation", ru: "ситуация", uk: "ситуація" }, example: "Das ist eine schwierige Situation." },
  { rank: 743, word: "Problem", article: "das", type: "noun", translations: { en: "problem", ru: "проблема", uk: "проблема" }, example: "Wir haben ein technisches Problem." },
  { rank: 745, word: "Niveau", article: "das", type: "noun", translations: { en: "level, standard", ru: "уровень, стандарт", uk: "рівень, стандарт" }, example: "Das Niveau ist sehr hoch." },
  { rank: 747, word: "Methode", article: "die", type: "noun", translations: { en: "method", ru: "метод, методика", uk: "метод, методика" }, example: "Welche Methode ist am besten?" },
  { rank: 749, word: "Strategie", article: "die", type: "noun", translations: { en: "strategy", ru: "стратегия", uk: "стратегія" }, example: "Wir brauchen eine neue Strategie." },
  { rank: 751, word: "Informationen", article: "die", type: "noun", translations: { en: "information", ru: "информация", uk: "інформація" }, example: "Wo finde ich mehr Informationen?" },
  { rank: 753, word: "Kommunikation", article: "die", type: "noun", translations: { en: "communication", ru: "общение, коммуникация", uk: "спілкування, комунікація" }, example: "Gute Kommunikation ist der Schlüssel." },
  { rank: 755, word: "Sprache", article: "die", type: "noun", translations: { en: "language, speech", ru: "язык, речь", uk: "мова, мовлення" }, example: "Welche Sprachen sprichst du?" },
  { rank: 757, word: "Wort", article: "das", type: "noun", translations: { en: "word", ru: "слово", uk: "слово" }, example: "Was bedeutet dieses Wort?" },
  { rank: 759, word: "Satz", article: "der", type: "noun", translations: { en: "sentence, set, price", ru: "предложение, набор, ставка", uk: "речення, набір, ставка" }, example: "Bilde einen Satz mit diesem Wort." },
];

/**
 * Words sorted ascending by corpus rank.
 * This is the canonical display order for the Top Words page.
 */
export const SORTED_FREQUENT_WORDS: FrequentWord[] = [...FREQUENT_WORDS]
  .sort((a, b) => a.rank - b.rank)
  .slice(0, 300);

/**
 * Maps each word's corpus `rank` to its 1-based display index in the sorted list.
 * Use this everywhere a visible "position number" or anchor id is needed so
 * the widget link, page anchor, and displayed number are all consistent.
 */
export const WORD_DISPLAY_INDEX: ReadonlyMap<number, number> = new Map(
  SORTED_FREQUENT_WORDS.map((w, i) => [w.rank, i + 1] as [number, number]),
);
